name: Build WASM & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  wasm:
    name: Build WebAssembly (em++)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Emscripten SDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
          actions-cache-folder: emsdk-cache

      - name: Build emtr.js / emtr.wasm
        run: |
          mkdir -p public/wasm
          em++ wasm-src/emtr_core.cpp wasm-src/emtr_wasm.cpp \
            -O3 -msimd128 \
            -s WASM=1 \
            -s MODULARIZE=1 -s EXPORT_ES6=1 -s EXPORT_NAME=createEmtr \
            -s ALLOW_MEMORY_GROWTH=1 \
            -s ENVIRONMENT=web,worker \
            -s FILESYSTEM=1 \
            -s EXPORTED_RUNTIME_METHODS='["FS","ccall","cwrap"]' \
            -s ASSERTIONS=2 \
            -s DISABLE_EXCEPTION_CATCHING=0 \
            --bind \
            -o public/wasm/emtr.js
          test -f public/wasm/emtr.wasm

      - name: Upload WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: emtr-wasm
          path: public/wasm/

  web:
    name: Build static site
    needs: wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download WASM artifact
        uses: actions/download-artifact@v4
        with:
          name: emtr-wasm
          path: public/wasm

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Expose commit SHA to Next.js (cache-bust WASM)
        run: echo "NEXT_PUBLIC_COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Install deps
        run: npm ci

      - name: Build (Next.js static export)
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    name: Deploy to GitHub Pages
    needs: web
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
